### ISSUE TITLE
Deleting member from list is causing deserialisation error

### ISSUE THREAD

**Issue by iegoshin** [banana-j/bananaj#51]
MailChimpConnection con = new MailChimpConnection("ApiKey");
		MailChimpList list = con.getList("List Id");
		Member member = list.getMember( "email hash" ); // existing member's id
		member.delete();
		member = list.getMember( "email hash" );

An I am getting this exception on the last line:
` java.lang.IllegalArgumentException: No enum constant com.github.alexanderwe.bananaj.model.list.member.MemberStatus.ARCHIVED
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.github.alexanderwe.bananaj.model.list.member.MemberStatus.valueOf(MemberStatus.java:12)
	at com.github.alexanderwe.bananaj.model.list.member.Member.parse(Member.java:104)
	at com.github.alexanderwe.bananaj.model.list.member.Member.<init>(Member.java:65)
	at com.github.alexanderwe.bananaj.model.list.MailChimpList.getMember(MailChimpList.java:152)`

**Comment by gscriver** [comment]
This issue has already been addressed in the upcoming release.
